services:
  mrp-db:
    image: postgres
    container_name: mrp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mrp_bosch
    ports:
      - "6578:5432"
    volumes:
      - mrp-db:/var/lib/postgresql/data/
    networks:
      - mrp_net

  api:
    depends_on:
      - mrp-db
    build: .
    container_name: mrp_backend
    ports:
      - "8080:8080"
    environment:
      URL_DB: jdbc:postgresql://mrp-db:5432/mrp_bosch
    networks:
      - mrp_net

volumes:
  mrp-db:

networks:
  mrp_net:
    driver: bridge